// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function Counter(props) {
  var setStatement = props.setStatement;
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  var handleIncrease = function (param) {
    setCount(function (prev) {
          return prev + 1 | 0;
        });
    setStatement(function (prev) {
          var lastIndex = prev.length - 1 | 0;
          var lastElement = Belt_Array.get(prev, lastIndex);
          console.log(lastElement, "last element");
          var lastElement2 = lastElement !== undefined ? lastElement : ({
                serial: lastIndex,
                amount: 0,
                total: 0
              });
          prev.push({
                serial: lastElement2.serial + 1 | 0,
                amount: 1,
                total: lastElement2.total + 1 | 0
              });
          return prev;
        });
  };
  var handleDecrease = function (param) {
    setCount(function (prev) {
          return prev - 1 | 0;
        });
  };
  var handleReset = function (param) {
    setCount(function (param) {
          return 0;
        });
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: "Counter"
                    }),
                JsxRuntime.jsx("div", {
                      children: match[0],
                      className: "border border-yellow-500 w-10 bg-yellow-100"
                    }),
                JsxRuntime.jsx("button", {
                      children: "Increase",
                      className: "border border-green-500 p-2 w-20 bg-green-100",
                      onClick: handleIncrease
                    }),
                JsxRuntime.jsx("button", {
                      children: "Decrease",
                      className: "border border-blue-700 p-2 w-20 bg-blue-100",
                      onClick: handleDecrease
                    }),
                JsxRuntime.jsx("button", {
                      children: "Reset",
                      className: "border border-red-700 p-2 w-20 bg-red-100",
                      onClick: handleReset
                    })
              ],
              className: "border border-pink-500 my-2 p-2"
            });
}

var make = Counter;

export {
  make ,
}
/* react Not a pure module */
