// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function getLastElementOfArray(arr) {
  var lastIndex = arr.length - 1 | 0;
  var lastElement = Belt_Array.get(arr, lastIndex);
  if (lastElement !== undefined) {
    return lastElement;
  } else {
    return {
            serial: lastIndex,
            amount: 0,
            total: 0
          };
  }
}

export {
  getLastElementOfArray ,
}
/* No side effect */
