// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Counter from "./components/Counter.res.mjs";
import * as Statement from "./components/Statement.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  var defaultState = [{
      serial: 0,
      amount: 0,
      total: 0
    }];
  var match = React.useState(function () {
        return defaultState;
      });
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx(Counter.make, {
                      setStatement: match[1]
                    }),
                JsxRuntime.jsx(Statement.make, {})
              ]
            });
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
