// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Counter from "./components/Counter.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  return JsxRuntime.jsx(JsxRuntime.Fragment, {
              children: Caml_option.some(JsxRuntime.jsx(Counter.make, {}))
            });
}

var make = App;

export {
  make ,
}
/* Counter Not a pure module */
