// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Counter from "./components/Counter.res.mjs";
import * as Statement from "./components/Statement.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx(Counter.make, {}),
                JsxRuntime.jsx(Statement.make, {})
              ]
            });
}

var make = App;

export {
  make ,
}
/* Counter Not a pure module */
